version: '3.1'

app-variables: &env-variables
  DATABASE_URI: ${DB_URI}
  SECRET_KEY: ${SECRET}
  ALLOWED_ORIGINS: ${CORS_LIST}
  SERVER_NAME: ${SERVER_NAME}
  ADMIN_PASSWORD_SALT: ${ADMIN_PASSWORD_SALT}
  SSH_KEY_NAME: id_rsa
  ADMIN_EMAIL: ${ADMIN_EMAIL}
  EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  PUBLIC_GIT_REPO: ${PUBLIC_GIT_REPO}
  PUBLIC_GIT_REPO_URL: ${PUBLIC_GIT_REPO_URL}
  REDIS_URL: ${REDIS_URL}

services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
      - /home/admin/proftest-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  app:
    restart: always
    image: ruslanperesy/pythonclassic:latest
    ports:
     - "5001:5000"
    depends_on:
     - postgres
     - redis
    volumes:
      - .:/app
      - /srv/git/pythonclassic:/srv/git
    environment:
      <<: *env-variables
  worker:
    restart: always
    image: ruslanperesy/pythonclassic:latest
    depends_on:
     - postgres
     - redis
    volumes:
      - .:/app
      - /srv/git/pythonclassic:/srv/git
    environment:
      <<: *env-variables
    command: make worker
  redis:
    redis:
    image: redis:6.2-alpine
  dashboard:
    build: ./dashboard
    image: ruslanperesy/rq-dashboard:latest
    ports:
      - 9181:9181
    command: rq-dashboard -H redis --username ${RQ_DASHBOARD_USER} --password ${RQ_DASHBOARD_PASSWORD}
    depends_on:
      - redis
