"""empty message

Revision ID: 00d8d1a52eba
Revises: 623e62d27b7e
Create Date: 2021-05-02 10:46:32.213331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d8d1a52eba'
down_revision = '623e62d27b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('code_placeholder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'code_placeholder')
    # ### end Alembic commands ###
