"""empty message

Revision ID: 29b2cf5f6ae6
Revises: e60eb867f040
Create Date: 2022-01-23 17:00:43.649832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b2cf5f6ae6'
down_revision = 'e60eb867f040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'public')
    # ### end Alembic commands ###
