"""empty message

Revision ID: 313f2a184419
Revises: 29b2cf5f6ae6
Create Date: 2022-02-01 21:34:02.228819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313f2a184419'
down_revision = '29b2cf5f6ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('replit_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'replit_url')
    # ### end Alembic commands ###
