"""empty message

Revision ID: 437948555897
Revises: a4be24a419e4
Create Date: 2021-04-01 08:53:05.805368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437948555897'
down_revision = 'a4be24a419e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('purpose', sa.String(length=15), nullable=True))
    op.add_column('submissions', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'rating')
    op.drop_column('submissions', 'purpose')
    # ### end Alembic commands ###
