"""empty message

Revision ID: 4ccd7d4db816
Revises: b41151588ad0
Create Date: 2021-04-06 11:44:07.806019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccd7d4db816'
down_revision = 'b41151588ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('meta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'meta')
    # ### end Alembic commands ###
