"""empty message

Revision ID: 623e62d27b7e
Revises: d7940b5fdc0d
Create Date: 2021-05-01 14:04:18.364551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623e62d27b7e'
down_revision = 'd7940b5fdc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('metainfo', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('metainfo', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('metainfo', sa.String(), nullable=True))
    op.add_column('feedbacks', sa.Column('metainfo', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('metainfo', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('metainfo', sa.String(), nullable=True))
    op.add_column('superusers', sa.Column('metainfo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('metainfo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'metainfo')
    op.drop_column('superusers', 'metainfo')
    op.drop_column('submissions', 'metainfo')
    op.drop_column('roles', 'metainfo')
    op.drop_column('feedbacks', 'metainfo')
    op.drop_column('categories', 'metainfo')
    op.drop_column('assessments', 'metainfo')
    op.drop_column('answers', 'metainfo')
    # ### end Alembic commands ###
