"""empty message

Revision ID: 6509e84388c7
Revises: 803c4b2801d5
Create Date: 2021-03-22 10:47:51.969073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6509e84388c7'
down_revision = '803c4b2801d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('type', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'type')
    # ### end Alembic commands ###
