"""empty message

Revision ID: ae0193de4ff7
Revises: 6509e84388c7
Create Date: 2021-03-23 11:00:47.701268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0193de4ff7'
down_revision = '6509e84388c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('submissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    # ### end Alembic commands ###
