"""empty message

Revision ID: d7940b5fdc0d
Revises: 8db176334500
Create Date: 2021-04-29 10:20:59.432075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7940b5fdc0d'
down_revision = '8db176334500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('metainfo', sa.String(), nullable=True))
    op.drop_column('questions', 'meta')
    op.drop_column('questions', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('meta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('type', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'metainfo')
    # ### end Alembic commands ###
