"""empty message

Revision ID: e2aee402284a
Revises: 0de1d220ee27
Create Date: 2022-01-19 00:15:06.567349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2aee402284a'
down_revision = '0de1d220ee27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('build_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'build_url')
    # ### end Alembic commands ###
