"""empty message

Revision ID: e60eb867f040
Revises: e2aee402284a
Create Date: 2022-01-22 12:15:21.358542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60eb867f040'
down_revision = 'e2aee402284a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'source_url')
    # ### end Alembic commands ###
